== About the OGC API – Tiles Code Sprint

An OGC Code Sprint is a collaborative and inclusive event driven by innovative and rapid programming with minimum process and organisation constraints to support the development of new applications and open standards. The *OGC API – Tiles Code Sprint* is organized by OGC and sponsored by Ordnance Survey.

http://portal.opengeospatial.org/files/?artifact_id=35326[Web Map Tile Service (WMTS)] is a well-established and implemented OGC standard, first issued in 2007. The http://docs.opengeospatial.org/is/17-069r3/17-069r3.html[OGC API – Feature – Part 1: Core] standard, published October 2019, is the first approved OGC standard to use https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md[OpenAPI] for describing a service that delivers geographic information over the web. This pattern is being adopted for all OGC API standards through the https://github.com/opengeospatial/oapi_common[OGC API - Common] candidate standard. https://github.com/opengeospatial/OGC-API-Tiles[OGC API – Tiles] seeks to implement this pattern for the delivery of tiled resources, such as raster or vector tiles. In this Code Sprint, participants will experiment with and validate the current draft https://github.com/opengeospatial/OGC-API-Tiles[OGC API – Tiles] specification.

The scope of the code sprint is to include API development and testing, using one or more implementations of https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md[OpenAPI] 3.0 (the successor of Swagger). Participants are welcome to bring partial or complete implementations of servers or clients to support the sprint. The Sprint will draw on the work of the OGC's http://portal.opengeospatial.org/files/?artifact_id=14416[Web Map Service (WMS)] Standards Working Group and will allow participants who haven't been members of this group detailed insight about the current plans for https://github.com/opengeospatial/OGC-API-Tiles[OGC API – Tiles]. Following an explanation of the current draft, participants will have the opportunity to experiment with parts of the specification and develop working services. This development can either be done with source data that participants bring to the event themselves or with source data made available by Ordnance Survey and other data sponsors, such as https://www.ordnancesurvey.co.uk/business-government/products/open-zoomstack[OS ZoomStack].  To complement work that is on-going in the https://www.ogc.org/projects/initiatives/vtp2[OGC Vector Tiles Pilot Phase 2] project, the Sprint participants will be encouraged to use OS ZoomStack.

The sprint will begin on April 23rd, 2020 at 09:00am UK time, and end on April 24th, 2020 at 17:00 (5 pm). The UK will be in daylight savings time, so these times are UTC+1. Ordnance Survey is sponsoring this event.

Register at https://www.eventbrite.com/e/osogc-sprint-tickets-100787600426
